export const Questions = [
{
      prompt:'https://www.countryflags.com/wp-content/uploads/pakistan-flag-png-large.png',
     answer:'pakistan',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/congo-democratic-republic-of-the-flag-png-large.png',
     answer:'république du congo-kinshasa',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/turkey-flag-png-large.png',
     answer:'turquie',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/cambodia-flag-png-large.png',
     answer:'cambodge',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/rwanda-flag-png-large.png',
     answer:'rwanda',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/flag-jpg-xl-18-scaled.jpg',
     answer:'belgique',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/greece-flag-png-large.png',
     answer:'grèce',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/czech-republic-flag-png-large.png',
     answer:'république tchèque',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/jordan-flag-png-large.png',
     answer:'jordanie',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/tajikistan-flag-png-large.png',
     answer:'tadjikistan',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/laos-flag-png-large.png',
     answer:'laos',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/serbia-flag-png-large.png',
     answer:'serbie',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/paraguay-flag-png-large.png',
     answer:'paraguay',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/kyrgyzstan-flag-png-large.png',
     answer:'kirghizistan',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/central-african-republic-flag-png-large.png',
     answer:'république centrafricaine',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/ireland-flag-png-large.png',
     answer:'irlande',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/georgia-flag-jpg-xl.jpg',
     answer:'géorgie',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/slovenia-flag-png-large.png',
     answer:'slovénie',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/mauritius-flag-png-large.png',
     answer:'maurice',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/malta-flag-png-large.png',
     answer:'malte',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/iceland-flag-png-large.png',
     answer:'islande',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/aruba-flag-jpg-xl.jpg',
     answer:'aruba',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/flag-jpg-xl-4-scaled.jpg',
     answer:'andorre',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/saint-kitts-and-nevis-flag-png-large.png',
     answer:'saint-christophe-et-niévès',},
{
      prompt:'https://www.countryflags.com/wp-content/uploads/liechtenstein-flag-png-large.png',
     answer:'liechtenstein',},
];
